### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by 737simpilot** [macmathan/Blocklists#4] opened 2018-05-20 19:49 UTC
Can you confirm whether updates are working for CIDRAM? I haven't seen any in the last few days for the block lists, especially Tor which is very disconcerting.

**Comment by macmathan** [comment] 2018-05-20 20:00
It is working as intended as far as I know so far.
See issue #2 for more details regarding the updates, as there are certain preconditions that has to be fulfilled for the updating to work.

**Comment by 737simpilot** [comment] 2018-05-21 02:08
Okay, I see that github is mentioned for the links in the updates page. I see you dropped support for tpen so that's why I haven't been getting updates to that.

**Comment by 737simpilot** [comment] 2018-05-21 17:34
Yeah, I just worry about that rDNS thing though because it has failed me in the past and just recently I saw that tpen did block someone. So it was a great fallback. I guess I could craft my own as a fallback.  

Question: Have you made any updates to the sigs yet? My cron says everything already updated.

**Comment by macmathan** [comment] 2018-05-21 18:02
You can check the file versions "live" on GitHub, just browse the files in the repository. The version number you are used to see in CIDRAM also exists in the file header. 

Remember what I mentioned in #2 about the need to update to a current version of CIDRAM for the updates to continue to work. Files on my domain are not updated and will be removed within a day or two.

If you want to craft your own list of TOR exit nodes the source is here: https://check.torproject.org/cgi-bin/TorBulkExitList.py

**Comment by Maikuolan** [comment] 2018-05-21 23:47
Worth noting: The recent changes and migration should be completely compatible with Cronable too (because it leverages the standard update process anyway, so should be the same, from an internals perspective), but it may still take a couple of goes of checking for updates for CIDRAM to figure out that there's a new location to use for fetching updates (meaning, the first few attempts that Cronable makes to update, may just state that everything's already up-to-date; it should start updating again after a couple of goes though, just the same as if you were doing it via the updates page yourself).

**Comment by 737simpilot** [comment] 2018-05-22 00:40
Yeah, cronable has updated CIDRAM twice now I believe so I know I'm running the latest version.

**Comment by 737simpilot** [comment] 2018-05-22 00:46
Okay, I might have an issue. I see here in Github that gcp_cidram.inc is version 2018.135.768, but my CIDRAM version is, GCP-2018.137.055.

I'm running CIDRAM version 1.6.0-DEV+18139775. 

The support links for the lists are all for Github. So that part has changed.

**Comment by 737simpilot** [comment] 2018-05-22 07:01
I have an error_log outside of public_html and it's producing errors when the cron runs, At first this was determined to be my host and there was no issue, but now I see a new entry I haven't seen before. This may or may not be related. 

[22-May-2018 00:00:02 America/Denver] PHP Notice:  Undefined variable: Data in /home/systechf/public_html/cidram/vault/frontend_functions.php on line 112

**Comment by Maikuolan** [comment] 2018-05-22 07:09
Eep.. Good catch. That's a (small) bug on my end. I'll get that sorted out now. Cheers.

**Comment by Maikuolan** [comment] 2018-05-22 07:26
(Re: "PHP Notice: Undefined variable: Data in ..."): Fixed. :+1:

**Comment by 737simpilot** [comment] 2018-05-22 18:48
Okay, when I went in to update CIDRAM manually, I saw that AWS and China had updates. First time I seen that in at least 4 days now. But no Google update.

**Comment by macmathan** [comment] 2018-05-22 18:51
Then you are good. AWS and CN got updated some hours ago. Google is stable for the moment. 
(Nothing new upstream)

**Comment by 737simpilot** [comment] 2018-05-22 22:55
I see. Okay, thanks.

**Comment by 737simpilot** [comment] 2018-05-23 23:20
Let me know if you push a Google update and I'll be sure to make sure that in fact it's updated. I know Google hasn't been updated in a while though since even before moving here to Github.

**Comment by macmathan** [comment] 2018-05-24 17:10
Closing this issue as it is confirmed that the updates are working from here.

**Closed by macmathan** 2018-05-24 17:10 UTC
Labels: duplicate
